global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'go-app'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Commented out nginx target for now
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx:80']
  #   metrics_path: /nginx_status
  #   scrape_interval: 10s 